name: parser_interface
description: Parser interface for the unwired and http_worker package.
version: 1.0.0
homepage: https://github.com/Ayush-Suman/parser_interface

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
